// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPaBgt_oedAQiUxlApwiPc9LCsx7W96pQ',
    appId: '1:416813571494:web:f43cadc45a0388780e8367',
    messagingSenderId: '416813571494',
    projectId: 'deliverit-394707',
    authDomain: 'deliverit-394707.firebaseapp.com',
    databaseURL: 'https://deliverit-394707-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'deliverit-394707.appspot.com',
    measurementId: 'G-YTC3XQYNKH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpG4daPlZ15RtFePznrDoobeRUralTbx8',
    appId: '1:416813571494:android:aec538060b3f326d0e8367',
    messagingSenderId: '416813571494',
    projectId: 'deliverit-394707',
    databaseURL: 'https://deliverit-394707-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'deliverit-394707.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAb0VVTubNOlT-M8p4L5FyZnJoR9unOnxs',
    appId: '1:416813571494:ios:cac3c0ed3da790250e8367',
    messagingSenderId: '416813571494',
    projectId: 'deliverit-394707',
    databaseURL: 'https://deliverit-394707-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'deliverit-394707.appspot.com',
    iosClientId: '416813571494-p968038bc1nf6q4t8cgivpsvm219rmbq.apps.googleusercontent.com',
    iosBundleId: 'com.finma.deliveritdriver.deliveritDriver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAb0VVTubNOlT-M8p4L5FyZnJoR9unOnxs',
    appId: '1:416813571494:ios:87238ff6d5ef10ef0e8367',
    messagingSenderId: '416813571494',
    projectId: 'deliverit-394707',
    databaseURL: 'https://deliverit-394707-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'deliverit-394707.appspot.com',
    iosClientId: '416813571494-23ca0o9ftuaa6a6kdjsmloovvgh4d0t3.apps.googleusercontent.com',
    iosBundleId: 'com.finma.deliveritdriver.deliveritDriver.RunnerTests',
  );
}
